### PR TITLE
Support Prefix & prompt upgrades

### PR DESCRIPTION
**Pull request by Muennighoff**
Running 

`/gpfsscratch/rech/six/commun/experiments/muennighoff/bloomckpt/6b3t0/tr13f-6b3-ml-t0-lmtoks168b-t0toks13b-prefix`
on
`super_glue,copa,None,"best_option"`
resulted in:

With prefix: Result: {'accuracy': 0.54}
Without prefix: Result: {'accuracy': 0.53}

### CODE REVIEW

**Comment by Muennighoff** [comment]
This is using the checkpoint of the bloom model after conversion to transformers.
The slurm script is here: https://github.com/bigscience-workshop/bigscience/blob/d98e577e5740304e200aedb74939aff900684d83/evaluation/results/tr13/tzeroeval/evaluate_t0.slurm

**Comment by stephenbach** [comment]
This repo is for reproducing the T0 paper. If changes are needed for BLOOM evaluation, perhaps they would be better put somewhere else?

**Comment by Muennighoff** [comment]
Agreed good point. We could make it a fork of t-zero on the bigscience org cc @thomasw21 ?

**Comment by thomasw21** [comment]
I don't think we need to fork, especially since it'll never get merged. Essentially we can write our own evaluation script in a new repo.

**Comment by VictorSanh** [comment]
gonna close that one pr since i understand you are working on another repo

**Pull request closed without merging**
